/**
 * Diff between two parsed corpora (2024 Official Journal -> 2026 consolidated), by logical ID and `node_hash`
 * (SHA-256 over heading + text; so a heading change counts as `changed`).
 *
 *  unchanged  same id, same hash
 *  changed    same id, different hash
 *  moved      id only in `from`, id only in `to`, identical hash, and that hash is unique on both sides
 *             (a unique 1:1 text match; ambiguous duplicates are NOT paired and stay removed/added)
 *  removed    id only in `from` and not moved
 *  added      id only in `to` and not moved
 * Deterministic: no clock, lists sorted by document order.
 */
import type { CorpusFile, NodeType, ProvisionNode } from "../parser/types.js";

export interface DiffRef {
  id: string;
  type: NodeType;
  node_hash: string;
}
export interface DiffChange {
  id: string;
  type: NodeType;
  from_node_hash: string;
  to_node_hash: string;
}
export interface DiffMove {
  from_id: string;
  to_id: string;
  type: NodeType;
  node_hash: string;
}
export interface DiffResult {
  lang: string;
  from: string;
  to: string;
  counts: { added: number; removed: number; changed: number; moved: number; unchanged: number };
  /** Removed/added nodes that share a hash with a node on the other side but could not be paired 1:1. */
  ambiguous_hash_matches: number;
  added: DiffRef[];
  removed: DiffRef[];
  changed: DiffChange[];
  moved: DiffMove[];
  unchanged: string[];
}

const ref = (n: ProvisionNode): DiffRef => ({ id: n.id, type: n.type, node_hash: n.node_hash });

export function diffNodes(from: ProvisionNode[], to: ProvisionNode[]): Omit<DiffResult, "lang" | "from" | "to"> {
  const fromById = new Map(from.map((n) => [n.id, n]));
  const toById = new Map(to.map((n) => [n.id, n]));

  const unchanged: string[] = [];
  const changed: DiffChange[] = [];
  const goneFrom: ProvisionNode[] = [];
  for (const n of from) {
    const t = toById.get(n.id);
    if (!t) goneFrom.push(n);
    else if (t.node_hash === n.node_hash) unchanged.push(n.id);
    else changed.push({ id: n.id, type: n.type, from_node_hash: n.node_hash, to_node_hash: t.node_hash });
  }
  const newInTo = to.filter((n) => !fromById.has(n.id));

  const byHash = (nodes: ProvisionNode[]): Map<string, ProvisionNode[]> => {
    const m = new Map<string, ProvisionNode[]>();
    for (const n of nodes) m.set(n.node_hash, [...(m.get(n.node_hash) ?? []), n]);
    return m;
  };
  const goneByHash = byHash(goneFrom);
  const newByHash = byHash(newInTo);

  const movedFromIds = new Set<string>();
  const movedToIds = new Set<string>();
  const moved: DiffMove[] = [];
  let ambiguous = 0;
  for (const n of newInTo) {
    const g = goneByHash.get(n.node_hash);
    const a = newByHash.get(n.node_hash);
    if (!g) continue;
    if (g.length === 1 && a?.length === 1) {
      const src = g[0] as ProvisionNode;
      moved.push({ from_id: src.id, to_id: n.id, type: n.type, node_hash: n.node_hash });
      movedFromIds.add(src.id);
      movedToIds.add(n.id);
    } else {
      ambiguous++;
    }
  }

  const removed = goneFrom.filter((n) => !movedFromIds.has(n.id)).map(ref);
  const added = newInTo.filter((n) => !movedToIds.has(n.id)).map(ref);
  return {
    counts: { added: added.length, removed: removed.length, changed: changed.length, moved: moved.length, unchanged: unchanged.length },
    ambiguous_hash_matches: ambiguous,
    added,
    removed,
    changed,
    moved,
    unchanged,
  };
}

export function diffCorpora(from: CorpusFile, to: CorpusFile): DiffResult {
  return { lang: from.lang, from: from.celex, to: to.celex, ...diffNodes(from.nodes, to.nodes) };
}

const oneLine = (s: string, max: number): string => (s.length > max ? `${s.slice(0, max - 1)}…` : s);

export function diffReportMarkdown(diff: DiffResult, from: CorpusFile, to: CorpusFile): string {
  const fromById = new Map(from.nodes.map((n) => [n.id, n]));
  const toById = new Map(to.nodes.map((n) => [n.id, n]));
  const c = diff.counts;
  const lines = [
    `# Diff ${diff.from} -> ${diff.to} (${diff.lang})`,
    "",
    `Source: (c) European Union, eur-lex.europa.eu. Generated by \`npm run parse\`; do not edit.`,
    "",
    "| class | nodes |",
    "|---|---|",
    `| unchanged | ${c.unchanged} |`,
    `| changed | ${c.changed} |`,
    `| moved | ${c.moved} |`,
    `| added | ${c.added} |`,
    `| removed | ${c.removed} |`,
    "",
    `Nodes in ${diff.from}: ${from.nodes.length}; in ${diff.to}: ${to.nodes.length}.`,
    `Removed/added nodes with an identical hash on the other side that could not be paired 1:1: ${diff.ambiguous_hash_matches}.`,
    "",
    "## Removed by type",
    "",
  ];
  const byType = new Map<string, number>();
  for (const r of diff.removed) byType.set(r.type, (byType.get(r.type) ?? 0) + 1);
  for (const [t, n] of [...byType].sort((a, b) => a[0].localeCompare(b[0]))) lines.push(`- ${t}: ${n}`);
  lines.push("", `## Removed (${diff.removed.length})`, "");
  for (const r of diff.removed) {
    const n = fromById.get(r.id);
    lines.push(`- \`${r.id}\` (${r.type}) ${oneLine((n?.heading || n?.text || "").replace(/\s+/g, " "), 90)}`);
  }
  lines.push("", `## Added (${diff.added.length})`, "");
  for (const r of diff.added) {
    const n = toById.get(r.id);
    lines.push(`- \`${r.id}\` (${r.type}) ${oneLine((n?.heading || n?.text || "").replace(/\s+/g, " "), 90)}`);
  }
  lines.push("", `## Moved (${diff.moved.length})`, "");
  for (const m of diff.moved) lines.push(`- \`${m.from_id}\` -> \`${m.to_id}\` (${m.type})`);
  lines.push("");
  return lines.join("\n");
}
