/** UI texts of the document checker page (EN/DE). Keys are used by data-i18n attributes in site/audit/index.html. */
import type { Pair } from "./i18n.js";

export const AUDIT_UI = {
  brand: { en: "EU AI Act workbench", de: "EU-AI-Act-Werkbank" },
  title: { en: "Document checker", de: "Dokument-Prüfer" },
  lead: {
    en: "Paste a text that mentions the EU AI Act. The checker looks for references to provisions, dates and quotations and compares them with the law in force on the date you choose.",
    de: "Fügen Sie einen Text ein, der den EU AI Act erwähnt. Der Prüfer sucht Verweise auf Vorschriften, Daten und Zitate und vergleicht sie mit dem Recht, das an Ihrem Stichtag gilt.",
  },
  privacyLead: { en: "Privacy:", de: "Datenschutz:" },
  privacy: { en: "Your text stays in your browser. Nothing is uploaded.", de: "Ihr Text bleibt in Ihrem Browser. Es wird nichts hochgeladen." },
  textLabel: { en: "Text to check", de: "Zu prüfender Text" },
  textPlaceholder: {
    en: "Paste a policy, a vendor answer, a slide or a chatbot answer here, for example: “Under Article 6(2) and Annex III, the obligations apply from 2 August 2026.”",
    de: "Fügen Sie hier eine Richtlinie, eine Anbieterantwort, eine Folie oder eine Chatbot-Antwort ein, zum Beispiel: „Nach Artikel 6 Absatz 2 und Anhang III gelten die Pflichten ab dem 2. August 2026.“",
  },
  dateLabel: { en: "Check as of", de: "Stichtag" },
  dateHint: { en: "The wording and dates in force on this day are used.", de: "Es gilt der Wortlaut und gelten die Fristen dieses Tages." },
  langLabel: { en: "Language of the text", de: "Sprache des Textes" },
  langAuto: { en: "Detect automatically", de: "Automatisch erkennen" },
  langEn: { en: "English", de: "Englisch" },
  langDe: { en: "German", de: "Deutsch" },
  check: { en: "Check text", de: "Text prüfen" },
  checking: { en: "Checking …", de: "Prüfe …" },
  exampleLabel: { en: "Try an example:", de: "Beispiel ausprobieren:" },
  clear: { en: "Clear", de: "Leeren" },
  noText: { en: "Please paste a text first.", de: "Bitte fügen Sie zuerst einen Text ein." },
  badDate: { en: "Please enter a valid date.", de: "Bitte geben Sie ein gültiges Datum ein." },
  failed: { en: "The check could not be run.", de: "Die Prüfung konnte nicht ausgeführt werden." },
  detected: { en: "Language used for the check:", de: "Für die Prüfung verwendete Sprache:" },
  resultH: { en: "Result", de: "Ergebnis" },
  resultFor: { en: "as of", de: "Stichtag" },
  textH: { en: "Your text with markers", de: "Ihr Text mit Markierungen" },
  textHint: { en: "Select a marked passage to jump to its finding.", de: "Wählen Sie eine markierte Stelle, um zum Befund zu springen." },
  findingsH: { en: "Findings", de: "Befunde" },
  filterLabel: { en: "Show", de: "Anzeigen" },
  filterAll: { en: "All", de: "Alle" },
  nothingShown: { en: "No findings of this kind.", de: "Keine Befunde dieser Art." },
  found: { en: "Found in the text", de: "Im Text gefunden" },
  expected: { en: "Expected", de: "Erwartet" },
  source: { en: "Source", de: "Quelle" },
  sources: { en: "Sources", de: "Quellen" },
  wording: { en: "Wording of", de: "Wortlaut von" },
  suggestion: { en: "Suggestion", de: "Vorschlag" },
  showInText: { en: "Show in text", de: "Im Text zeigen" },
  copyReport: { en: "Copy report (Markdown)", de: "Bericht kopieren (Markdown)" },
  copied: { en: "Copied", de: "Kopiert" },
  copyFailed: { en: "Copy failed", de: "Kopieren fehlgeschlagen" },
  downloadJson: { en: "Download JSON", de: "JSON herunterladen" },
  noteTruncated: { en: "(shortened)", de: "(gekürzt)" },
  footer: { en: "Not legal advice. The consolidated text is not legally authentic; only the Official Journal is binding.", de: "Keine Rechtsberatung. Die konsolidierte Fassung ist nicht rechtsverbindlich; verbindlich ist nur das Amtsblatt." },
  noscript: { en: "This tool needs JavaScript. Your text is processed in the browser only.", de: "Dieses Werkzeug benötigt JavaScript. Ihr Text wird nur im Browser verarbeitet." },
  navObligations: { en: "Obligations navigator", de: "Pflichten-Navigator" },
  navAudit: { en: "Document checker", de: "Dokument-Prüfer" },
  navVerify: { en: "Verify a record", de: "Nachweis prüfen" },
  skip: { en: "Skip to content", de: "Zum Inhalt springen" },
} satisfies Record<string, Pair>;

export type AuditUiKey = keyof typeof AUDIT_UI;
