/** UI texts of the obligations navigator page (EN/DE). Keys are used by data-i18n attributes in site/obligations/index.html. */
import type { Pair } from "./i18n.js";

export const OBLIGATIONS_UI = {
  brand: { en: "EU AI Act workbench", de: "EU-AI-Act-Werkbank" },
  skip: { en: "Skip to content", de: "Zum Inhalt springen" },
  navObligations: { en: "Obligations navigator", de: "Pflichten-Navigator" },
  navAudit: { en: "Document checker", de: "Dokument-Prüfer" },
  navVerify: { en: "Verify a record", de: "Nachweis prüfen" },
  title: { en: "Obligations navigator", de: "Pflichten-Navigator" },
  lead: {
    en: "Answer a few questions about your organisation and your AI system. You get the obligations that apply now and the ones that are coming, each with the provision, the date and the exact wording.",
    de: "Beantworten Sie einige Fragen zu Ihrer Organisation und Ihrem KI-System. Sie erhalten die Pflichten, die jetzt gelten und die noch kommen, jeweils mit Fundstelle, Datum und genauem Wortlaut.",
  },
  privacyLead: { en: "Privacy:", de: "Datenschutz:" },
  privacy: { en: "Your answers stay in your browser. Nothing is uploaded.", de: "Ihre Antworten bleiben in Ihrem Browser. Es wird nichts hochgeladen." },
  exampleLabel: { en: "Start from an example:", de: "Mit einem Beispiel beginnen:" },
  formH: { en: "Your situation", de: "Ihre Situation" },
  dateLabel: { en: "Date checked", de: "Stichtag" },
  dateHint: { en: "The consolidated text applies from 27 July 2026.", de: "Die konsolidierte Fassung gilt ab dem 27. Juli 2026." },
  yes: { en: "Yes", de: "Ja" },
  no: { en: "No", de: "Nein" },
  unsure: { en: "Not sure", de: "Weiß nicht" },
  selectNone: { en: "None of these / not sure", de: "Keiner davon / weiß nicht" },
  selectUnset: { en: "Not specified", de: "Keine Angabe" },
  moreQuestions: { en: "Select a role to see more questions.", de: "Wählen Sie eine Rolle, um weitere Fragen zu sehen." },
  evaluate: { en: "Show my obligations", de: "Meine Pflichten anzeigen" },
  evaluating: { en: "Working …", de: "Berechne …" },
  reset: { en: "Start over", de: "Neu beginnen" },
  needRole: { en: "Please select at least one role first.", de: "Bitte wählen Sie zuerst mindestens eine Rolle." },
  badDate: { en: "Please enter a valid date.", de: "Bitte geben Sie ein gültiges Datum ein." },
  dateTooEarly: { en: "This tool covers the consolidated text in force from 27 July 2026. Please choose a later date.", de: "Dieses Werkzeug deckt die konsolidierte Fassung ab, die seit dem 27. Juli 2026 gilt. Bitte wählen Sie ein späteres Datum." },
  failed: { en: "The result could not be computed.", de: "Das Ergebnis konnte nicht berechnet werden." },
  dataFailed: { en: "The questions could not be loaded. Please reload the page.", de: "Die Fragen konnten nicht geladen werden. Bitte laden Sie die Seite neu." },
  emptyH: { en: "Your result appears here", de: "Hier erscheint Ihr Ergebnis" },
  emptyText: { en: "Answer the questions on the left, or start from an example, and choose “Show my obligations”.", de: "Beantworten Sie die Fragen links oder beginnen Sie mit einem Beispiel und wählen Sie „Meine Pflichten anzeigen“." },
  resultH: { en: "Your classification", de: "Ihre Einstufung" },
  asOf: { en: "as of", de: "Stichtag" },
  nApplicable: { en: "apply now", de: "gelten jetzt" },
  nUpcoming: { en: "upcoming", de: "kommen noch" },
  nDepends: { en: "depend on conditions", de: "hängen ab" },
  timelineH: { en: "Timeline", de: "Zeitleiste" },
  today: { en: "Today", de: "Heute" },
  alreadyApply: { en: "already apply", de: "gelten bereits" },
  moreItems: { en: "more", de: "weitere" },
  checklistH: { en: "Checklist", de: "Checkliste" },
  openH: { en: "Open questions", de: "Offene Fragen" },
  openIntro: { en: "Your answer to these questions could change the result. Some need a legal assessment, which this tool does not make.", de: "Ihre Antwort auf diese Fragen könnte das Ergebnis ändern. Manche erfordern eine rechtliche Bewertung, die dieses Werkzeug nicht vornimmt." },
  openCount: { en: "open questions", de: "offene Fragen" },
  goToQuestion: { en: "Answer this", de: "Beantworten" },
  needsAssessment: { en: "Needs a legal assessment", de: "Rechtliche Bewertung nötig" },
  badgeOmnibus: { en: "Changed by Omnibus", de: "Durch Omnibus geändert" },
  badgeLegal: { en: "Legal assessment needed", de: "Rechtliche Bewertung nötig" },
  badgeCaveat: { en: "Date caveat", de: "Hinweis zum Datum" },
  badgeVerified: { en: "Wording verified against the corpus", de: "Wortlaut gegen den Korpus geprüft" },
  badgeNotVerified: { en: "Wording could not be verified", de: "Wortlaut nicht prüfbar" },
  appliesTo: { en: "Applies to", de: "Gilt für" },
  roleAll: { en: "everyone in scope", de: "alle im Anwendungsbereich" },
  provisions: { en: "Provisions", de: "Fundstellen" },
  showWording: { en: "Show the exact wording", de: "Wortlaut anzeigen" },
  wordingDe: { en: "German wording of the provision", de: "Deutscher Wortlaut der Vorschrift" },
  literalReading: { en: "A literal reading of Article 113 gives", de: "Nach wörtlicher Lesart des Artikels 113 gilt" },
  routeDates: { en: "Dates by route", de: "Daten je nach Weg" },
  contentNote: { en: "", de: "Hinweis: Titel und Zusammenfassungen der Pflichten sind auf Englisch. Den deutschen Wortlaut der Vorschrift zeigt jede Karte unter „Wortlaut anzeigen“." },
  copyMd: { en: "Copy checklist (Markdown)", de: "Checkliste kopieren (Markdown)" },
  downloadCsv: { en: "Download CSV", de: "CSV herunterladen" },
  copyLink: { en: "Copy link to share", de: "Link zum Teilen kopieren" },
  copied: { en: "Copied", de: "Kopiert" },
  copyFailed: { en: "Copy failed", de: "Kopieren fehlgeschlagen" },
  linkNote: { en: "The link contains your answers in its address part. They are not sent anywhere; whoever opens the link sees them.", de: "Der Link enthält Ihre Antworten im Adressteil. Sie werden nirgendwohin gesendet; wer den Link öffnet, sieht sie." },
  footer: { en: "Not legal advice. The consolidated text is not legally authentic; only the Official Journal is binding.", de: "Keine Rechtsberatung. Die konsolidierte Fassung ist nicht rechtsverbindlich; verbindlich ist nur das Amtsblatt." },
  noscript: { en: "This tool needs JavaScript. Your answers are processed in the browser only.", de: "Dieses Werkzeug benötigt JavaScript. Ihre Antworten werden nur im Browser verarbeitet." },
} satisfies Record<string, Pair>;

export type ObligationsUiKey = keyof typeof OBLIGATIONS_UI;
